### ISSUE TITLE
Latest Update Broke Markdown CSS

### ISSUE THREAD

**Issue by GaryHal75** [th3jesta/ha-lcars#106] opened 2024-08-27 13:23 UTC
I just updated my Home Assistant instance on a Raspberry Pi 4B:
Core
2024.8.3
Supervisor
2024.08.0
Operating System
13.1
Frontend
20240809.0

I cleared the cache and reloaded home assistant and noticed that the markdown CSS classes for non functional styling (.header-contained, .middle-contained etc) are no longer styled specifically.  They are all just single color divs with no detail as you can see in the image here:

<img width="418" alt="Screenshot 2024-08-27 at 9 15 59 AM" src="https://github.com/user-attachments/assets/ad514e30-f967-45ea-8b9a-2bf8d4d6241b">

I did the most recent update to HA-LCARS-2.3.0 at the same time as the Home Assistant update and then noticed these issues.

**Comment by schmiegelt** [comment] 2024-08-30 09:41
Hi, 
this seems to be a duplicate of #103 and #104.
The root cause lies within card-mod (used by this theme): [Issue here](https://github.com/thomasloven/lovelace-card-mod/issues/392)

I am also waiting for a fix :-)

**Comment by derkork** [comment] 2024-09-05 15:18
I wonder if there would be a different way of implementing this skinning without depending on card-mod. The last commit on card-mod was 6 months ago and there doesn't seem to be a lot of activity over there anymore.

**Comment by GaryHal75** [comment] 2024-09-05 20:56
<img width="685" alt="image" src="https://github.com/user-attachments/assets/ff728fad-5b58-46f5-8c4e-51f51a3107b6">

I still see the class there and I can target it using cardmod and add a pink border for example.  I think the issue is probably in the CSS itself and how it is selecting the pseudo elements.  It may not be applying the styles to the shadow root like it should be.  That's my guess.

**Comment by TimDG** [comment] 2024-09-11 11:46
Looking at the HTML: the class is not added to the ha-card:

<img width="1067" alt="image" src="https://github.com/user-attachments/assets/fef7e3bf-fd2f-43e2-b798-e7ab6a9b423f">

Manually adding the `middle` class to the `<ha-card>` element fixes the look:

<img width="1054" alt="image" src="https://github.com/user-attachments/assets/24bf4fb0-126a-4e4d-acf4-f038797ad808">

**Comment by th3jesta** [comment] 2024-09-11 11:55
Please see https://github.com/thomasloven/lovelace-card-mod/issues/392
We have tested outside of HA-LCARS with the same result. card-mod is unable to target markdown cards on initial load of the page. If you subsequently call the reload themes action after a page has loaded (I mapped it to a button card), it will apply the class to the card. 

Oddly, just applying a style to the card via card mod works every time.

**Comment by TimDG** [comment] 2024-09-11 12:48
Sorry about that, I forgot to add that the reloading of the theme does not help in this case (hence why I thought it was unrelated). 

I've added the automation that was suggested in that card-mod ticket (to reload the theme every 10 seconds). This fixes the headers, but not the other cards.

I do see that there is a difference in behavior:

My header card is a simple markdown card. When the page is loaded, this gets the proper classes, however the `style` tag created by card-mod is empty.
  
<img width="281" alt="image" src="https://github.com/user-attachments/assets/4944f59c-37c7-4f02-a828-b0d655a8bc99">

This resolves itself by calling the reload themes action.

On the other hand, the other cards do not have the correct classes, but their `style` tag contains all necessary CSS.

![image](https://github.com/user-attachments/assets/23d75452-6382-4408-b714-088060f12a63)

This is not fixed by reloading the theme.

If this too is related to the card-mod issue, I'll gladly post this update there as well.

**Closed** 2024-10-04 17:04 UTC
