### ISSUE TITLE
HA-LCARS-2.3.0

### ISSUE THREAD

**Issue by WolfgangFuchs** [th3jesta/ha-lcars#104] opened 2024-08-12 17:32 UTC
Hello, 
first of all...I love LCARS. For me one of the best themes ever!

Now to my problem. After I updated to the current version, some HEADER / FOOTER are no longer displayed as usual --> see attachment.
Any idea/hint/solution?

Thank you.

Best regards
Wolfgang Fuchs

**Comment by seamansrl** [comment] 2024-08-12 22:54
I have the same problem, I always solved the failures by myself but this time I can't find the problem. I understand that it is not in the theme but in the card-mod.

**Comment by tmguinn** [comment] 2024-08-12 23:14
Same here. All headers and footers have rounded ends. Also is affecting my weather forecast item.

**Comment by th3jesta** [comment] 2024-08-13 05:41
This is a duplicate of #103. Unfortunately, it's a bug in card-mod. I created https://github.com/thomasloven/lovelace-card-mod/issues/392 in card-mod's repo.

**Closed** 2024-10-13 13:30 UTC
